version: '2'
services:
  php:
    container_name: users_php
    build:
      context: .
      dockerfile: php/Dockerfile
    user: '1000'
    # environment:
    #     PHP_IDE_CONFIG: "serverName=users.localhost"
    # extra_hosts: 
    #   - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/var/www/app/:rw
      - ./php/conf/upload_max_size.ini:/usr/local/etc/php/conf.d/upload_max_size.ini
    depends_on:
      - mysql  
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    links:
      - 'php'
    volumes:
      - ./app:/var/www/app/:rw
      - ./nginx/conf.d:/etc/nginx/conf.d/:ro
    depends_on:
      - php
    labels:
      kompose.service.type: LoadBalancer  
  mysql:
    image: mariadb:10.3
    ports:
      - '3306:3306'
    environment:
      - 'MARIADB_ROOT_USER=root'
      - 'MARIADB_ROOT_PASSWORD=qwerty'
      - 'MARIADB_DATABASE=users'
      - 'MARIADB_USER=users'
      - 'MARIADB_PASSWORD=qwerty'
      - 'ALLOW_EMPTY_PASSWORD=no'
    volumes:
      - users_mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql  
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'    
  maildev:
    image: maildev/maildev
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "8025:1025"
  minio:
    image: quay.io/minio/minio
    volumes:
      - ${HOME}/minio/data:/data
    environment:
      #MINIO_ACCESS_KEY: gKemAPmVMag6Q3aj
      #MINIO_SECRET_KEY: XMg4pLw8N6hcMhRNIdT6Ch0vIRnv97YB
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data    
    ports:
      - "9000:9000"
      - "9001:9001"
    user: ${USER}  
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3  
volumes:
  users_mysql_data:
        