version: '2'
services:
  php-nginx:
    build:
      context: .
      dockerfile: php/prod-Dockerfile
    user: ${UID}  
    depends_on:
      - mysql
  mysql:
    image: mariadb:10.3
    ports:
      - '3306:3306'
    environment:
      - 'MARIADB_ROOT_USER=root'
      - 'MARIADB_ROOT_PASSWORD=qwerty'
      - 'MARIADB_DATABASE=users'
      - 'MARIADB_USER=users'
      - 'MARIADB_PASSWORD=qwerty'
      - 'ALLOW_EMPTY_PASSWORD=no'
    volumes:
      - users-mysql-prod-data:/var/lib/mysql
  redis:
    image: 'redis:7.0'
    ports:
      - '6379:6379'    
  maildev:
    image: maildev/maildev
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8025:1080"
  minio:
    image: quay.io/minio/minio
    volumes:
      - ${HOME}/minio/data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data    
    ports:
      - "9000:9000"
      - "9001:9001"
volumes:
  users-mysql-prod-data:
        