version: '2'
services:
  php:
    build:
      dockerfile: php/Dockerfile
    user: '1000'  
    volumes:
      - ./app:/var/www/app/:rw
    depends_on:
      - mysql  
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    links:
      - 'php'
    volumes:
      - ./app:/var/www/app/:rw
      - ./nginx-conf:/etc/nginx/conf.d/:ro
    depends_on:
      - php
  mysql:
    image: mariadb:10.3
    ports:
      - '3306:3306'
    environment:
      - 'MARIADB_ROOT_USER=root'
      - 'MARIADB_ROOT_PASSWORD=qwerty'
      - 'MARIADB_DATABASE=users'
      - 'MARIADB_USER=users'
      - 'MARIADB_PASSWORD=qwerty'
      - 'ALLOW_EMPTY_PASSWORD=no'
    volumes:
      - users_mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql  
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'    
  maildev:
    image: maildev/maildev
    ports:
      - "8025:1080"
  minio:
    image: minio/minio
    ports:
      - target: 9001
        published: ${MINIO_PORT:-9001}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: minio-store
        target: /data
        volume:
          nocopy: true
    environment:
      MINIO_ACCESS_KEY: test_access_key
      MINIO_SECRET_KEY: test_secret_key
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: qwerty
    command: server /data    
volumes:
  users_mysql_data:
  minio-store:
        