version: '2'
services:
  php:
    container_name: users_php
    build:
      context: .
      dockerfile: php/Dockerfile
    user: '1000'
    environment:
        PHP_IDE_CONFIG: "serverName=users.localhost"
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/var/www/app/:rw
      - ./php/conf/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./php/conf/upload_max_size.ini:/usr/local/etc/php/conf.d/upload_max_size.ini
    depends_on:
      - mysql  
  nginx:
    image: nginx:1.23
    ports:
      - '80:80'
    links:
      - 'php'
    volumes:
      - ./app:/var/www/app/:rw
      - ./nginx/conf-dev.d:/etc/nginx/conf.d/:ro
    depends_on:
      - php
  mysql:
    image: mariadb:10.3
    ports:
      - '3306:3306'
    environment:
      - 'MARIADB_ROOT_USER=root'
      - 'MARIADB_ROOT_PASSWORD=qwerty'
      - 'MARIADB_DATABASE=users'
      - 'MARIADB_USER=users'
      - 'MARIADB_PASSWORD=qwerty'
      - 'ALLOW_EMPTY_PASSWORD=no'
    volumes:
      - users_mysql_data:/var/lib/mysql
  redis:
    image: 'redis:7.0'
    ports:
      - '6379:6379'    
  maildev:
    image: maildev/maildev
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=8025
    ports:
      - "8025:1080"
  minio:
    image: quay.io/minio/minio
    volumes:
      - ${HOME}/minio/data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data    
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3  
volumes:
  users_mysql_data:
        